source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
link_with 'BarbackSwift', 'BarbackSwiftTests'
pod 'Appirater'
pod 'MBProgressHUD', '~> 0.8'
pod 'RNBlurModalView', '~> 0.1.0'
pod 'WSCoachMarksView', '~> 0.2'
