fastlane_version "1.36.2"

default_platform :ios


platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
    
    increment_build_number

    # xctool # run the tests of your app
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    sigh
    gym # Build your app - more options available
    deliver(force: true)
  end

  after_all do |lane|
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end